return {
	inter = {
		semibold = Font.fromId(12187365364, Enum.FontWeight.SemiBold),
		bold = Font.fromId(12187365364, Enum.FontWeight.Bold),
		heavy = Font.fromId(12187365364, Enum.FontWeight.Heavy),
	},
	fredoka = {
		semibold = Font.fromName("FredokaOne", Enum.FontWeight.SemiBold),
		bold = Font.fromName("FredokaOne", Enum.FontWeight.Bold),
		heavy = Font.fromName("FredokaOne", Enum.FontWeight.Heavy),
		regular = Font.fromName("FredokaOne"),
	},
}
